name: "Build kernels"

env:
  OUT_DIR: "out"

on:
  workflow_dispatch:
    inputs:
      kernelSourceURL:
        description: "Custom kernel source URL"
        required: true
        type: string
        default: "https://github.com/topnotchfreaks/kernel_msm-5.15"
      kernelPrivateSource:
        description: "Is private source?"
        required: false
        type: boolean
        default: false
      kernelBranch:
        description: "Kernel branch (default if empty)"
        required: false
        type: string
        default: "codelinaro"
      kernelDevice:
        description: "Device (used for defconfig)"
        required: true
        type: string
        default: "gki"
      kernelSourceName:
        description: "Kernel source name"
        required: true
        type: string
        default: "kernel_msm-5.15"
      localVersion:
        description: "Custom localversion name (e.g., -mybuild)"
        required: false
        type: string
        default: ""
      kernelSUChoice:
        description: "Choose KernelSU version"
        required: true
        default: "KernelSU"
        type: choice
        options:
          - "None"
          - "KernelSU-Next-SuSFS"

jobs:
  Set-repos:
    name: "🐂 Parse repository"
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.generate-matrix.outputs.repos }}
    steps:
      - name: "😄 Checkout"
        uses: actions/checkout@v4

      - name: "😆 Generate Matrix"
        id: generate-matrix
        run: |
          repos='[
            {
              "kernelSource": {
                "repo": "",
                "branch": ""
              },
              "params": {
                "ARCH": "arm64",
                "CROSS_COMPILE": "aarch64-linux-gnu-",
                "CLANG_TRIPLE": "aarch64-linux-gnu-",
                "AR": "llvm-ar",
                "CC": "clang"
              }
            }
          ]'

          repos=$(echo "$repos" | jq --arg url "${{ github.event.inputs.kernelSourceURL }}" --arg branch "${{ github.event.inputs.kernelBranch }}" '.[].kernelSource.repo = $url | .[].kernelSource.branch = $branch')

          echo "repos<<EOF" >> $GITHUB_OUTPUT
          echo "$repos" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  Build-Kernel:
    name: "🐎 Build kernel"
    runs-on: ubuntu-latest
    needs:
      - Set-repos
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        repos: ${{ fromJSON(needs.Set-repos.outputs.repos) }}
    env:
      kernelDir: ${{ github.event.inputs.kernelSourceName }}_${{ github.event.inputs.kernelDevice }}
      kernelName: ${{ github.event.inputs.kernelSourceName }}
      kernelRepo: ${{ github.event.inputs.kernelSourceURL }}
      kernelBranch: ${{ github.event.inputs.kernelBranch }}
      kernelDevice: ${{ github.event.inputs.kernelDevice }}
      DEFCONFIG_NAME: ${{ github.event.inputs.kernelDevice }}_defconfig

    steps:
      - name: "✨ Setup workspace"
        run: |
          mkdir -p $kernelDir

          echo "BUILD_TIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

          sudo apt-get update
          sudo apt-get install -y build-essential bc curl flex cpio ccache rsync git zip dwarves libelf-dev gcc-aarch64-linux-gnu libssl-dev python3 clang lld llvm llvm-dev

      - name: "🌟 Clone kernel source => (${{ env.kernelRepo }})"
        working-directory: ./${{ env.kernelDir }}
        env:
          PRIVATE_SOURCE: ${{ github.event.inputs.kernelSourceURL }}
        run: |
          set -x
          if [ "${{ github.event.inputs.kernelPrivateSource }}" == "true" ]; then
            if [[ "$PRIVATE_SOURCE" == *"github.com"* ]]; then
              PRIVATE_SOURCE="${PRIVATE_SOURCE#https://github.com/}"
              OWNER=$(echo "$PRIVATE_SOURCE" | cut -d'/' -f1)
              REPO_PREFIX="https://$OWNER:${{ secrets.PRIVATE_REPO_TOKEN }}@github.com/"
            elif [[ "$PRIVATE_SOURCE" == *"gitlab.com"* ]]; then
              PRIVATE_SOURCE="${PRIVATE_SOURCE#https://gitlab.com/}"
              OWNER=$(echo "$PRIVATE_SOURCE" | cut -d'/' -f1)
              REPO_PREFIX="https://$OWNER:${{ secrets.PRIVATE_REPO_TOKEN }}@gitlab.com/"
            else
              echo "Unsupported repository source: $PRIVATE_SOURCE"
              exit 1
            fi
            
            git clone --recursive --branch ${{ github.event.inputs.kernelBranch }} \
              "$REPO_PREFIX$PRIVATE_SOURCE" ${{ env.kernelName }} --depth=1
          else
            git clone --recursive --branch ${{ github.event.inputs.kernelBranch }} \
              ${{ github.event.inputs.kernelSourceURL }} ${{ env.kernelName }} --depth=1
          fi

      - name: "💫 Get Toolchains"
        run: |
          set -e
          
          get_latest_github_release() {
            local repo_url="$1"
            latest_url=$(curl -sL "https://api.github.com/repos/$repo_url/releases/latest" | grep "browser_download_url.*tar.gz" | cut -d '"' -f 4 | head -n 1)
            
            if [[ -z "$latest_url" ]]; then
              echo "❌ Failed to fetch latest release from $repo_url!"
              exit 1
            fi
      
            printf "%s" "$latest_url"
          }

          clang_url=$(get_latest_github_release "greenforce-project/greenforce_clang")

          mkdir -p clang
          wget --progress=bar:force -O "clang/clang.tar.gz" "$clang_url" || { echo "❌ Failed to download Clang!"; exit 1; }
          tar -xf clang/clang.tar.gz -C clang || { echo "❌ Extraction failed!"; exit 1; }
          rm -f clang/clang.tar.gz
          
          CLANG_PATH=$(find clang -type d -name "bin" | head -n 1)
          CLANG_PATH="${{ github.workspace }}/${CLANG_PATH}"
      
          echo "CLANG_PATH=$CLANG_PATH" >> $GITHUB_ENV
          echo "$CLANG_PATH" >> $GITHUB_PATH
      
          export PATH="$CLANG_PATH:$PATH"
          export CLANG_TRIPLE="aarch64-linux-gnu-"
          export CC="ccache clang"
          export AR="llvm-ar"
          export AS="llvm-as"
          export NM="llvm-nm"
          export OBJCOPY="llvm-objcopy"
          export OBJDUMP="llvm-objdump"
          export STRIP="llvm-strip"
      
          clang --version

      - name: 📐 Setup swap 25G
        uses: pierotofy/set-swap-space@master
        with:
            swap-size-gb: 25

      - name: 📐 Tune Swap
        run: |
            echo "vm.swappiness=80" | sudo tee -a /etc/sysctl.conf
            sudo sysctl -p
        
      - name: "📥 Restore ccache Cache"
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: "⚡ Configure ccache"
        run: |
            echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> $GITHUB_ENV
            echo "CC='ccache clang'" >> $GITHUB_ENV
            echo "PATH=/usr/lib/ccache:$PATH" >> $GITHUB_ENV
          
      - name: "😎 Set args for GKI kernels"
        id: generate-args
        working-directory: ./${{ env.kernelDir }}
        env:
            params: "${{ toJSON(matrix.repos.params) }}"
        run: |
            args="-j$(nproc --all)"
            if [ -n "${{ env.OUT_DIR }}" ]; then
              mkdir -p $(pwd)/${{ env.OUT_DIR }}
              args="$args O=$(pwd)/${{ env.OUT_DIR }}"
            fi
            args="$args ARCH=arm64 LLVM=1 LTO=thin"
            args="$args CROSS_COMPILE=aarch64-linux-gnu-"
            args="$args CLANG_TRIPLE=aarch64-linux-gnu-"
            args="$args AR=llvm-ar"
            args="$args CC=clang"
            echo "args=$args" >> $GITHUB_OUTPUT

      - name: "🛠 Set localversion name in defconfig"
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        env:
          LOCALVERSION: ${{ github.event.inputs.localVersion }}
        run: |
          if [ -n "$LOCALVERSION" ]; then
            echo "CONFIG_LOCALVERSION=\"$LOCALVERSION\"" >> arch/arm64/configs/${{ env.DEFCONFIG_NAME }}
          fi

      - name: "🛠 Setup kernel Tweaks"
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        run: |
          set -e
          
          log() {
            echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"
          }
        
          apply_patch() {
            local patch="$1"
            local error_msg="$2"
        
            log "Attempting to apply patch: $(basename "$patch")"
            if ! patch -p1 < "$patch"; then
              log "Warning: Some hunks failed while applying patch $(basename "$patch")"
            fi
          }

          PATCH_URL="https://raw.githubusercontent.com/topnotchfreaks/kernel_patches/main/0001-fs-lineageos-disguise.patch"
          PATCH_FILE="0001-fs-lineageos-disguise.patch"
        
          log "Downloading patch from $PATCH_URL"
          curl -L -o "$PATCH_FILE" "$PATCH_URL"
        
          if [ ! -f "$PATCH_FILE" ]; then
            log "Patch file $PATCH_FILE does not exist after download"
            exit 1
          fi
        
          apply_patch "$PATCH_FILE"
        
          log "✅ Patch applied successfully"

      - name: "😋 Update KernelSU-Next + Next-SuSFS"
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        if: ${{ github.event.inputs.kernelSUChoice == 'KernelSU-Next-SuSFS' }}
        run: |
          if [ -d "./KernelSU-Next" ]; then
            rm -rf "./KernelSU-Next"
          fi
          if [ -d "./drivers/kernelsu" ]; then
            rm -rf "./drivers/kernelsu"
          fi

          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs

      - name: 😋 Setup SUSFS
        if: ${{ github.event.inputs.kernelSUChoice == 'KernelSU-Next-SuSFS' }}
        env: 
          ARCH: ${{ steps.generate-args.outputs.ARCH }}
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        run: |
          set -ex
        
          log() {
            echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"
          }
        
          apply_patch() {
            local patch="$1"
            local error_msg="$2"
        
            log "Attempting to apply patch: $(basename "$patch")"
            if ! patch -p1 < "$patch"; then
              log "Warning: Some hunks failed while applying patch $(basename "$patch")"
            fi
          }
        
          PATCH_URL="https://raw.githubusercontent.com/topnotchfreaks/kernel_patches/main/0001-Implement-SUSFS-v1.5.7-manual-hooks.patch"
          PATCH_FILE="0001-Implement-SUSFS-v1.5.7-manual-hooks.patch"
        
          log "Downloading SUSFS patch from $PATCH_URL"
          curl -L -o "$PATCH_FILE" "$PATCH_URL"
        
          if [ ! -f "$PATCH_FILE" ]; then
            log "Patch file $PATCH_FILE does not exist after download"
            exit 1
          fi
        
          apply_patch "$PATCH_FILE"
        
          log "✅ External SUSFS patch applied successfully"

      - name: ⚙️ Add SUSFS configs
        if: ${{ github.event.inputs.kernelSUChoice == 'KernelSU-Next-SuSFS' }}
        env:
          ARCH: ${{ steps.generate-args.outputs.ARCH }}
          DEFCONFIG_NAME: ${{ env.DEFCONFIG_NAME }}
          kernelName: ${{ env.kernelName }}
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        run: |
          set -ex
      
          log() {
            echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"
          }
      
          CONFIG_FILE="./arch/${ARCH}/configs/${DEFCONFIG_NAME}"
          mkdir -p "$(dirname "$CONFIG_FILE")"
      
          # Configuration settings
          CONFIGS=(
          "CONFIG_KSU=y"
          "CONFIG_KSU_WITH_KPROBES=n"
          "CONFIG_KSU_SUSFS=y"
          "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y"
          "CONFIG_KSU_SUSFS_SUS_PATH=y"
          "CONFIG_KSU_SUSFS_SUS_MOUNT=y"
          "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y"
          "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y"
          "CONFIG_KSU_SUSFS_SUS_KSTAT=y"
          "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y"
          "CONFIG_KSU_SUSFS_TRY_UMOUNT=y"
          "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y"
          "CONFIG_KSU_SUSFS_SPOOF_UNAME=y"
          "CONFIG_KSU_SUSFS_ENABLE_LOG=y"
          "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y"
          "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y"
          "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y"
          "CONFIG_KSU_SUSFS_SUS_SU=n"
          "CONFIG_TMPFS_XATTR=y"
          "CONFIG_TMPFS_POSIX_ACL=y"
          "CONFIG_OVERLAY_FS=y"
          "CONFIG_OVERLAY_FS_REDIRECT_DIR=y"
          "CONFIG_OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW=y"
          )
      
          for config in "${CONFIGS[@]}"; do
            echo "$config" >> "$CONFIG_FILE"
          done
      
          log "✅ SUSFS configs added to $CONFIG_FILE"
          log "Current config contents:"
          cat "$CONFIG_FILE"            

      - name: "📝 Append custom Makefile line"
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        run: |
          # temporary clang compiler fixup
          echo 'KBUILD_CFLAGS += -Wno-default-const-init-unsafe' >> Makefile
          echo "Custom Makefile line added successfully"

      - name: "👍 Make defconfig"
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        env:
          args: ${{ steps.generate-args.outputs.args }}
        run: |
          make ${{ env.args }} ${{ env.DEFCONFIG_NAME }}

      - name: "🎶 Build kernel"
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        env:
          args: ${{ steps.generate-args.outputs.args }}
        run: |
          export KBUILD_BUILD_USER="Action"
          export KBUILD_BUILD_HOST="GitHub"

          ccache -z
        
          make ${args} \
            LLVM=1 \
            LTO=thin \
            CC="ccache clang" \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            STRIP=llvm-strip \
            -j$(nproc --all)
        
      - name: "📤 Save ccache Cache"
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-ccache-${{ github.sha }}
        
      - name: "📦 Pack Anykernel3"
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        run: |
          set -e
      
          [ ! -d "AnyKernel3" ] && git clone https://github.com/topnotchfreaks/AnyKernel3.git --depth=1
      
          KERNEL_IMAGE_PATH="../${{ env.OUT_DIR }}/arch/arm64/boot/Image"
          if [ ! -f "$KERNEL_IMAGE_PATH" ]; then
            KERNEL_IMAGE_PATH=$(find ../${{ env.OUT_DIR }}/arch/arm64/boot -name "Image*" | head -n 1)
            if [ -z "$KERNEL_IMAGE_PATH" ]; then
              echo "Error: No kernel image found."
              exit 1
            fi
          fi
      
          cp "$KERNEL_IMAGE_PATH" AnyKernel3/Image
      
          ZIP_NAME="${{ env.kernelBranch }}_${{ env.BUILD_TIME }}.zip"
          cd AnyKernel3
          zip -r9 "../$ZIP_NAME" * -x .git/*
          cd ..

          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
      
      - name: "⬆️ Upload Kernel Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: Anykernel3_${{ env.kernelBranch }}_${{ env.BUILD_TIME }}.zip
          path: ./${{ env.kernelDir }}/${{ env.kernelName }}/${{ env.kernelBranch }}_${{ env.BUILD_TIME }}.zip
          retention-days: 7

      - name: "📤 Send kernel ZIP to Telegram"
        run: |
          UPLOAD_ZIP_NAME="Anykernel3_${{ env.kernelBranch }}_${{ env.BUILD_TIME }}.zip"

          mv "./${{ env.kernelDir }}/${{ env.kernelName }}/${{ env.kernelBranch }}_${{ env.BUILD_TIME }}.zip" \
             "./${{ env.kernelDir }}/${{ env.kernelName }}/${UPLOAD_ZIP_NAME}"

          ANYKERNEL3_PATH="./${{ env.kernelDir }}/${{ env.kernelName }}/${UPLOAD_ZIP_NAME}"

          if [[ -f "$ANYKERNEL3_PATH" ]]; then
            curl -s -F document=@"$ANYKERNEL3_PATH" \
                 -F caption="✅ Custom Kernel Build $(date '+%Y-%m-%d %H:%M:%S')" \
                 -F chat_id=${{ secrets.TELEGRAM_USER_ID }} \
                 "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument"
          else
            curl -s -X POST \
                 -d chat_id=${{ secrets.TELEGRAM_USER_ID }} \
                 -d text="❌ Kernel build failed or no output file found." \
                 "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
          fi
